input {
  gelf {
    port => 12201
    protocol => "udp"
    use_udp => true
  }
}

filter {
  if [message] {
    mutate {
      add_field => { "raw_message" => "%{message}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    ssl_enabled => false
    index => "foodbridge-logs-%{+YYYY.MM.dd}"
    data_stream => false
    ilm_enabled => false
  }
}
